#!/bin/sh

VERSION=$(git rev-list HEAD | wc -l | tr -d '[:space:]')
echo $VERSION

VERSION=$(cat package.json \
  | grep version \
  | head -1 \
  | awk -F: '{ print $2 }' \
  | sed 's/[^0-9.]*\([0-9.]*\).*/\1/g' \
  | tr -d '[:space:]')
 
PACKAGE_VERSION=$(echo ${VERSION} | awk -F. -v OFS=. 'NF==1{print ++$NF}; NF>1{if(length($NF+1)>length($NF))$(NF-1)++; $NF=sprintf("%0*d", length($NF), ($NF+1)%(10^length($NF))); print}' )

echo $PACKAGE_VERSION

sed -i -e "s/$VERSION/$PACKAGE_VERSION/g" package.json
git add package.json
